In [1]:
try:
    from git_nomad import pull_nomad
except:
    import sys; sys.path.insert(0, '..')
    from git_nomad import pull_nomad
    
import socket
if socket.gethostname() == 'SPA-DESKTOP':
    remote_path = r"D:\Work_TU\Documents\nomad"
else:
    remote_path = r"C:\Users\martijnsparnaa\Eclipse_Python_NOMAD\nomad_trb_paper"
repo_path, repo = pull_nomad(remote_path, 'master')
print(repo_path.resolve())

import os
import time
os.chdir(repo_path)
headcommit = repo.head.commit
committed_date = time.strftime("%a, %d %b %Y %H:%M", time.localtime(headcommit.committed_date))
print(f'{headcommit}: {committed_date} - {headcommit.message}')

C:\Users\martijnsparnaa\Jupyterlab_notebooks\trb_analysis\nomad
4327d5a94643413d48d19b348b0e4c68eec76b5a: Wed, 14 Jul 2021 11:03 - Merge branch 'master' of C:/Users/martijnsparnaa/Eclipse_Python_NOMAD/nomad_trb_paper



In [2]:
from pathlib import Path
from NOMAD import nomad_model

pd = Path(r'C:\Users\martijnsparnaa\surfdrive\PhD\Activity scheduler\Scenarios\paper_scenarios')

xmlFlNm = pd.joinpath('trb_paper_base.xml')
model = nomad_model.createAndRun(xmlFlNm, seed=10)

ModuleNotFoundError: No module named 'NOMAD'

In [9]:
import numpy as np
from scipy import stats

rng = np.random.default_rng()

SAMPLE_SIZE = 3000

for loc in [0,0.2]:
    for size in [10,30,100,1000]:
        sig_values = np.zeros((SAMPLE_SIZE,1), dtype=float)
        for ii in range(SAMPLE_SIZE):
            adStats = stats.anderson_ksamp([rng.normal(size=size), rng.normal(loc=loc, size=size)])
            sig_values[ii] = adStats.significance_level
        consec = np.cumsum(sig_values == 0.25)
        np.argwhere((consec[:1] - consec[1:]) > 1)
        print(f'Loc = {loc:.1f}, Size = {size:4d}, mean_sig_value = {np.mean(sig_values):.4f}, at_25 = {np.sum(sig_values == 0.25)}')




<ipython-input-9-b4b257e2555c>:12: UserWarning: p-value capped: true value larger than 0.25
  adStats = stats.anderson_ksamp([rng.normal(size=size), rng.normal(loc=loc, size=size)])


Loc = 0.0, Size =   10, mean_sig_value = 0.2156, at_25 = 2196


<ipython-input-9-b4b257e2555c>:12: UserWarning: p-value floored: true value smaller than 0.001
  adStats = stats.anderson_ksamp([rng.normal(size=size), rng.normal(loc=loc, size=size)])


Loc = 0.0, Size =   30, mean_sig_value = 0.2171, at_25 = 2225
Loc = 0.0, Size =  100, mean_sig_value = 0.2198, at_25 = 2266
Loc = 0.0, Size = 1000, mean_sig_value = 0.2202, at_25 = 2253
Loc = 0.2, Size =   10, mean_sig_value = 0.2085, at_25 = 2102
Loc = 0.2, Size =   30, mean_sig_value = 0.1965, at_25 = 1915
Loc = 0.2, Size =  100, mean_sig_value = 0.1526, at_25 = 1290
Loc = 0.2, Size = 1000, mean_sig_value = 0.0030, at_25 = 0


In [2]:
import numpy as np

rng = np.random.default_rng()
print(rng.choice(np.arange(1,20), 5, False).tolist())
print(rng.choice(np.arange(1,20), 5, False))
print(rng.choice(np.arange(1,20), 5, False))
print(rng.choice(np.arange(1,20), 5, False, shuffle=False))
print(rng.choice(np.arange(1,20), 5, False, shuffle=False))
print(rng.choice(np.arange(1,20), 5, False, shuffle=False))

[17, 7, 15, 12, 3]
[ 9 10  5 13 15]
[19  7  1 16 17]
[ 4 13  2  7 18]
[ 4  9  7  5 14]
[11  3 12 18 14]


In [62]:
import numpy as np
from scipy import stats

rng = np.random.default_rng()

SAMPLE_SIZE = 3000
size = 100

a = [1,2,3,4,5,6]

locs = [1,0.5,1.5]

samples = []
samples.append(rng.normal(loc=rng.choice(locs,1), size=size))
print()
sig_values = []
stat_values = []

base = samples[0]

for ii in range(100):
    new = np.concatenate((base, rng.normal(loc=rng.choice(locs,1), size=size)))
    adStats = stats.anderson_ksamp([base, new])
    sig_values.append(adStats.significance_level) 
    stat_values.append(adStats.statistic)
    base = new
    
print(sig_values)
print(stat_values)

    


<ipython-input-62-0af3ee900abf>:23: UserWarning: p-value capped: true value larger than 0.25
  adStats = stats.anderson_ksamp([base, new])


[0.25, 0.12023008107901507, 0.011217977356636493, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
[-0.2922869009142379, 1.052065270297226, 3.621326186420544, -0.5525560493323285, -1.2246633204390183, -0.42901760702657843, -0.1614003387389942, -0.8637744934484176, 0.0837527452387257, -0.6976961157733013, -1.1470176179110345, -1.2252824353563194, -0.5490114479196442, -1.210494302152525, -0.7167622188334631, -1.2543422348738331, -0.1877906897531688, -0.942037134975

In [2]:
import numpy as np
from scipy import stats

rng = np.random.default_rng()

SAMPLE_SIZE = 3000
size = 100

a = [1,2,3,4,5,6]

locs = [1,0.5,1.5]

samples = []
samples.append(rng.normal(loc=rng.choice(locs,1), size=size))
print()
sig_values = []
stat_values = []

base = samples[0]

for ii in range(100):
    new = np.concatenate((base, rng.normal(loc=rng.choice(locs,1), size=size)))
    cvmStats = stats.cramervonmises_2samp(base, new)
    sig_values.append(cvmStats.pvalue) 
    stat_values.append(cvmStats.statistic)
    base = new
    
print(sig_values)
#print(stat_values)



[0.09062628098412939, 0.8768997266525071, 0.98882422576518, 0.4241796835756646, 0.05843506371220841, 0.2367599488856309, 0.48773328815243533, 1.0, 0.27573095025289807, 0.7039708897798964, 0.4440857173589414, 0.47847503482808385, 0.8347800882892509, 0.836409075431205, 0.9998932411818371, 0.9995273056049153, 0.9796395484922041, 0.9999999997922716, 0.8268464933527055, 0.9583805447371262, 0.9625566713770806, 0.9998875273030062, 0.99543949166266, 0.9644120700085085, 0.8118011867044244, 0.999999972638195, 0.9489704795319408, 0.689056110443926, 0.982810950399693, 0.8373902682784697, 0.9149438821340709, 1.0, 0.9914780807442617, 0.9323235593054244, 0.9492660689096788, 1.0, 1.0, 0.9235605793976698, 0.9165482715652974, 1.0, 1.0, 1.0, 0.9576762452626142, 1.0, 0.9902560518902496, 0.9999495681428148, 1.0, 0.9961395226224079, 0.9999074385189894, 0.9666868033032416, 0.999999911283343, 0.9997537925081756, 0.9965090606104521, 0.9999710697047245, 0.9953316965147854, 0.9783627851442266, 0.995979338058245

In [3]:
from contact_analysis import ExperimentRunner

experimentRunner = ExperimentRunner('test.scen', 'test.lrcm')

experimentRunner._run_experiment()


[0 1 4 7 9]
[0 1 4 7 9]
[6 0 8 4 8]
[6 0 8 4 8]
[3 5 1 2 9]
[3 5 1 2 9]
[6 8 1 6 9]
[6 8 1 6 9]
[1 7 4 6 2]
[1 7 4 6 2]
[7 2 1 5 4]
[7 2 1 5 4]
[9 2 2 4 9]
[9 2 2 4 9]
[1 9 8 1 9]
[1 9 8 1 9]
[3 2 2 8 6]
[3 2 2 8 6]
[1 0 6 5 8]
[1 0 6 5 8]
[3 4 6 0 5]
[3 4 6 0 5]
[6 1 8 3 4]
[6 1 8 3 4]
[8 1 4 9 1]
[8 1 4 9 1]
[5 2 7 2 3]
[5 2 7 2 3]
[5 8 4 5 6]
[5 8 4 5 6]
[6 5 6 5 4]
[6 5 6 5 4]
[4 6 2 3 9]
[4 6 2 3 9]
[5 1 5 9 4]
[5 1 5 9 4]
[8 3 5 7 6]
[8 3 5 7 6]
[9 2 6 2 8]
[9 2 6 2 8]
[3 2 1 0 7]
[3 2 1 0 7]
[5 6 4 4 3]
[5 6 4 4 3]
[4 6 8 9 4]
[4 6 8 9 4]
[8 9 6 3 1]
[8 9 6 3 1]
[9 5 8 8 4]
[9 5 8 8 4]
[4 0 3 7 5]
[4 0 3 7 5]
[6 7 0 6 4]
[6 7 0 6 4]
[7 6 0 5 9]
[7 6 0 5 9]
[9 1 0 3 5]
[9 1 0 3 5]
[6 3 5 6 4]
[6 3 5 6 4]


In [5]:
from _collections import deque

a = deque('', 5)

for ii in range(10):
    a.append(ii)
    print(a)

deque([0], maxlen=5)
deque([0, 1], maxlen=5)
deque([0, 1, 2], maxlen=5)
deque([0, 1, 2, 3], maxlen=5)
deque([0, 1, 2, 3, 4], maxlen=5)
deque([1, 2, 3, 4, 5], maxlen=5)
deque([2, 3, 4, 5, 6], maxlen=5)
deque([3, 4, 5, 6, 7], maxlen=5)
deque([4, 5, 6, 7, 8], maxlen=5)
deque([5, 6, 7, 8, 9], maxlen=5)
